apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: goserver
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'
