apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: emiliosheinz/gitops-fc
  newTag: 960f082350ae16f8c559b3fb7b9c5615c20239db
